version: 2
sources: 
  - name: raw
    description: "Raw data loaded from CSV files"
    schema: main
    tables:
      - name: raw_customers
      - name: raw_products
      - name: raw_sellers
      - name: raw_order_items 
      - name: raw_order_payments
      - name: raw_orders
      - name: raw_order_reviews
      - name: raw_product_category_name_translation
